### ISSUE TITLE
 at com.corochann.androidtvapptutorial.ui.background.PicassoBackgroundManager$PicassoBackgroundManagerTarget.onBitmapFailed(PicassoBackgroundManager.java:160)

### ISSUE THREAD

**Issue by MuthuKrishnanO** [corochann/AndroidTVappTutorial#8]

**Comment by MuthuKrishnanO** [comment]
when click the last row card  it show error " at com.corochann.androidtvapptutorial.ui.background.PicassoBackgroundManager$PicassoBackgroundManagerTarget.onBitmapFailed(PicassoBackgroundManager.java:160)"
